apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appoptics-controller
rules:
- apiGroups:
  - appoptics.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - '*'
