required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

#[[constraint]]
#  name = "k8s.io/kubernetes"
#  version = "~1.10"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~7.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[override]]
  name = "github.com/appoptics/appoptics-api-go"
  revision = "15d9e654ec9fea4a16425501445aa1969fb63242"
#[[constraint]]
#  name = "k8s.io/apiextensions-apiserver"
#  version = "kubernetes-1.10.0"

# gengo needs to be manually pinned to the version listed in code-generators
# Gopkg.toml, because the k8s project does not produce Gopkg.toml files & dep
# does not parse the Godeps.json file to determine revisions to use.
[[override]]
  name = "k8s.io/gengo"
  revision = "b6c426f7730e6d66e6e476a85d1c3eb7633880e0"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

