appVersion: "1.0"
description: A Helm chart AppOptics Dashboard, Services & Alerts Management on K8s
name: appoptics-controller
version: 0.1.1
maintainers:
- name: Beau Rudder
  email: beau.rudder@solarwinds.com
