# Default values for appoptics-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

image:
  registry: docker.io
  repository: appoptics/appoptics-controller-controller
  tag: "0.1"
  pullPolicy: IfNotPresent

resyncInSecs: 60


resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi

# Remember, log level is an int!
logLevel: 1

nodeSelector: {}

tolerations: []

affinity: {}